openapi: 3.0.3
info:
  title: Reqres API
  description: API for managing users and resources, as defined in the Reqres API Collection.
  version: 1.0.0
servers:
  - url: https://reqres.in/api
    description: Reqres API base URL
paths:
  /users:
    get:
      summary: List Users
      description: Retrieves a paginated list of users.
      operationId: listUsers
      parameters:
        - name: x-api-key
          in: header
          required: true
          schema:
            type: string
            example: reqres-free-v1
        - name: page
          in: query
          required: false
          schema:
            type: integer
            example: 1
        - name: delay
          in: query
          required: false
          schema:
            type: integer
            example: 3
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: object
                properties:
                  page:
                    type: integer
                    example: 1
                  per_page:
                    type: integer
                    example: 6
                  total:
                    type: integer
                    example: 12
                  total_pages:
                    type: integer
                    example: 2
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        email:
                          type: string
                          example: george.bluth@reqres.in
                        first_name:
                          type: string
                          example: George
                        last_name:
                          type: string
                          example: Bluth
                        avatar:
                          type: string
                          example: https://reqres.in/img/faces/1-image.jpg
    post:
      summary: Create User
      description: Creates a new user.
      operationId: createUser
      parameters:
        - name: x-api-key
          in: header
          required: true
          schema:
            type: string
            example: reqres-free-v1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - job
              properties:
                name:
                  type: string
                  example: morpheus
                job:
                  type: string
                  example: leader
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "123"
                  name:
                    type: string
                    example: morpheus
                  job:
                    type: string
                    example: leader
                  createdAt:
                    type: string
                    format: date-time
                    example: 2025-05-06T12:00:00.000Z
  /users/{id}:
    get:
      summary: Get Single User
      description: Retrieves a single user by ID.
      operationId: getSingleUser
      parameters:
        - name: x-api-key
          in: header
          required: true
          schema:
            type: string
            example: reqres-free-v1
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: "2"
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 2
                      email:
                        type: string
                        example: janet.weaver@reqres.in
                      first_name:
                        type: string
                        example: Janet
                      last_name:
                        type: string
                        example: Weaver
                      avatar:
                        type: string
                        example: https://reqres.in/img/faces/2-image.jpg
        '404':
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: User not found
    put:
      summary: Update User (PUT)
      description: Updates a user using PUT method.
      operationId: updateUserPut
      parameters:
        - name: x-api-key
          in: header
          required: true
          schema:
            type: string
            example: reqres-free-v1
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: "2"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - job
              properties:
                name:
                  type: string
                  example: morpheus
                job:
                  type: string
                  example: zion resident
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    example: morpheus
                  job:
                    type: string
                    example: zion resident
                  updatedAt:
                    type: string
                    format: date-time
                    example: 2025-05-06T12:00:00.000Z
    patch:
      summary: Update User (PATCH)
      description: Partially updates a user using PATCH method.
      operationId: updateUserPatch
      parameters:
        - name: x-api-key
          in: header
          required: true
          schema:
            type: string
            example: reqres-free-v1
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: "2"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: morpheus
                job:
                  type: string
                  example: zion resident
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    example: morpheus
                  job:
                    type: string
                    example: zion resident
                  updatedAt:
                    type: string
                    format: date-time
                    example: 2025-05-06T12:00:00.000Z
    delete:
      summary: Delete User
      description: Deletes a user by ID.
      operationId: deleteUser
      parameters:
        - name: x-api-key
          in: header
          required: true
          schema:
            type: string
            example: reqres-free-v1
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: "2"
      responses:
        '204':
          description: User deleted successfully
          content: {}
  /unknown:
    get:
      summary: List Resources
      description: Retrieves a list of resources.
      operationId: listResources
      responses:
        '200':
          description: A list of resources
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        name:
                          type: string
                          example: cerulean
                        year:
                          type: integer
                          example: 2000
                        color:
                          type: string
                          example: "#98B2D1"
                        pantone_value:
                          type: string
                          example: 15-4020
  /unknown/{id}:
    get:
      summary: Get Single Resource
      description: Retrieves a single resource by ID.
      operationId: getSingleResource
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: "2"
      responses:
        '200':
          description: Resource found
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 2
                      name:
                        type: string
                        example: fuchsia rose
                      year:
                        type: integer
                        example: 2001
                      color:
                        type: string
                        example: "#C74375"
                      pantone_value:
                        type: string
                        example: 17-2031
  /register:
    post:
      summary: Register User
      description: Registers a new user.
      operationId: registerUser
      parameters:
        - name: x-api-key
          in: header
          required: true
          schema:
            type: string
            example: reqres-free-v1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  example: eve.holt@reqres.in
                password:
                  type: string
                  example: pistol
      responses:
        '200':
          description: Registration successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 4
                  token:
                    type: string
                    example: QpwL5tke4Pnpja7X4
        '400':
          description: Registration failed (e.g., missing password)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Missing password
  /login:
    post:
      summary: Login User
      description: Authenticates a user and returns a token.
      operationId: loginUser
      parameters:
        - name: x-api-key
          in: header
          required: true
          schema:
            type: string
            example: reqres-free-v1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  example: eve.holt@reqres.in
                password:
                  type: string
                  example: cityslicka
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: QpwL5tke4Pnpja7X4
        '400':
          description: Login failed (e.g., missing password)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Missing password
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        email:
          type: string
          example: george.bluth@reqres.in
        first_name:
          type: string
          example: George
        last_name:
          type: string
          example: Bluth
        avatar:
          type: string
          example: https://reqres.in/img/faces/1-image.jpg
    Resource:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: cerulean
        year:
          type: integer
          example: 2000
        color:
          type: string
          example: "#98B2D1"
        pantone_value:
          type: string
          example: 15-4020
    Error:
      type: object
      properties:
        error:
          type: string
          example: User not found
