openapi: 3.0.0
info:
  title: Reqres API Example
  description: Example OpenAPI doc for Reqres.in
  version: 1.0.0
servers:
  - url: https://reqres.in/api
paths:
  /users:
    get:
      summary: Get list of users
      responses:
        '200':
          description: Successful response
